version: '3'
services:
  product-app:
    image: paulo/product:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=1234
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/productdb
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
